//! Code generated by sqlc-gen-rust. SHOULD NOT EDIT.
//! sqlc version: v1.30.0
//! sqlc-gen-rust version: v0.1.10-extras.1

use deadpool_postgres::tokio_postgres::types::ToSql;
pub struct SaveLayoutStateRow {
  pub id: uuid::Uuid,
  pub user_id: String,
  pub context_key: String,
  pub settings: serde_json::Value,
  pub created_at: jiff::Timestamp,
  pub updated_at: jiff::Timestamp,
}
impl SaveLayoutStateRow {
  pub fn from_row(
    row: &deadpool_postgres::tokio_postgres::Row,
  ) -> Result<Self, deadpool_postgres::tokio_postgres::Error> {
    Ok(Self {
      id: row.try_get(0)?,
      user_id: row.try_get(1)?,
      context_key: row.try_get(2)?,
      settings: row.try_get(3)?,
      created_at: row.try_get(4)?,
      updated_at: row.try_get(5)?,
    })
  }
}
pub struct SaveLayoutState<'a> {
  id: uuid::Uuid,
  user_id: &'a str,
  context_key: &'a str,
  settings: &'a serde_json::Value,
}
impl<'a> SaveLayoutState<'a> {
  pub const QUERY: &'static str = r"INSERT INTO layout_state (id, user_id, context_key, settings, created_at, updated_at)
VALUES ($1, $2, $3, $4, now(), now())
ON CONFLICT (user_id, context_key) DO UPDATE SET
  settings = EXCLUDED.settings,
  updated_at = now()
RETURNING id, user_id, context_key, settings, created_at, updated_at";
  pub async fn query_one(
    &self,
    client: &impl deadpool_postgres::GenericClient,
  ) -> Result<SaveLayoutStateRow, deadpool_postgres::tokio_postgres::Error> {
    let row = client.query_one(Self::QUERY, &self.as_slice()).await?;
    SaveLayoutStateRow::from_row(&row)
  }
  pub async fn query_opt(
    &self,
    client: &impl deadpool_postgres::GenericClient,
  ) -> Result<Option<SaveLayoutStateRow>, deadpool_postgres::tokio_postgres::Error> {
    let row = client.query_opt(Self::QUERY, &self.as_slice()).await?;
    match row {
      Some(row) => Ok(Some(SaveLayoutStateRow::from_row(&row)?)),
      None => Ok(None),
    }
  }
  pub fn as_slice(&self) -> [&(dyn ToSql + Sync); 4] {
    [&self.id, &self.user_id, &self.context_key, &self.settings]
  }
}
impl<'a> SaveLayoutState<'a> {
  pub const fn builder() -> SaveLayoutStateBuilder<'a, ((), (), (), ())> {
    SaveLayoutStateBuilder {
      fields: ((), (), (), ()),
      _phantom: std::marker::PhantomData,
    }
  }
}
pub struct SaveLayoutStateBuilder<'a, Fields = ((), (), (), ())> {
  fields: Fields,
  _phantom: std::marker::PhantomData<&'a ()>,
}
impl<'a, UserId, ContextKey, Settings>
  SaveLayoutStateBuilder<'a, ((), UserId, ContextKey, Settings)>
{
  pub fn id(
    self,
    id: uuid::Uuid,
  ) -> SaveLayoutStateBuilder<'a, (uuid::Uuid, UserId, ContextKey, Settings)> {
    let ((), user_id, context_key, settings) = self.fields;
    let _phantom = self._phantom;
    SaveLayoutStateBuilder {
      fields: (id, user_id, context_key, settings),
      _phantom,
    }
  }
}
impl<'a, Id, ContextKey, Settings> SaveLayoutStateBuilder<'a, (Id, (), ContextKey, Settings)> {
  pub fn user_id(
    self,
    user_id: &'a str,
  ) -> SaveLayoutStateBuilder<'a, (Id, &'a str, ContextKey, Settings)> {
    let (id, (), context_key, settings) = self.fields;
    let _phantom = self._phantom;
    SaveLayoutStateBuilder {
      fields: (id, user_id, context_key, settings),
      _phantom,
    }
  }
}
impl<'a, Id, UserId, Settings> SaveLayoutStateBuilder<'a, (Id, UserId, (), Settings)> {
  pub fn context_key(
    self,
    context_key: &'a str,
  ) -> SaveLayoutStateBuilder<'a, (Id, UserId, &'a str, Settings)> {
    let (id, user_id, (), settings) = self.fields;
    let _phantom = self._phantom;
    SaveLayoutStateBuilder {
      fields: (id, user_id, context_key, settings),
      _phantom,
    }
  }
}
impl<'a, Id, UserId, ContextKey> SaveLayoutStateBuilder<'a, (Id, UserId, ContextKey, ())> {
  pub fn settings(
    self,
    settings: &'a serde_json::Value,
  ) -> SaveLayoutStateBuilder<'a, (Id, UserId, ContextKey, &'a serde_json::Value)> {
    let (id, user_id, context_key, ()) = self.fields;
    let _phantom = self._phantom;
    SaveLayoutStateBuilder {
      fields: (id, user_id, context_key, settings),
      _phantom,
    }
  }
}
impl<'a> SaveLayoutStateBuilder<'a, (uuid::Uuid, &'a str, &'a str, &'a serde_json::Value)> {
  pub const fn build(self) -> SaveLayoutState<'a> {
    let (id, user_id, context_key, settings) = self.fields;
    SaveLayoutState {
      id,
      user_id,
      context_key,
      settings,
    }
  }
}
#[derive(serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct GetLayoutStateRow {
  pub id: uuid::Uuid,
  pub user_id: String,
  pub context_key: String,
  pub settings: serde_json::Value,
  pub created_at: jiff::Timestamp,
  pub updated_at: jiff::Timestamp,
}
impl GetLayoutStateRow {
  pub fn from_row(
    row: &deadpool_postgres::tokio_postgres::Row,
  ) -> Result<Self, deadpool_postgres::tokio_postgres::Error> {
    Ok(Self {
      id: row.try_get(0)?,
      user_id: row.try_get(1)?,
      context_key: row.try_get(2)?,
      settings: row.try_get(3)?,
      created_at: row.try_get(4)?,
      updated_at: row.try_get(5)?,
    })
  }
}
pub struct GetLayoutState<'a> {
  user_id: &'a str,
  context_key: &'a str,
}
impl<'a> GetLayoutState<'a> {
  pub const QUERY: &'static str = r"SELECT id, user_id, context_key, settings, created_at, updated_at
FROM layout_state
WHERE user_id = $1 AND context_key = $2";
  pub async fn query_one(
    &self,
    client: &impl deadpool_postgres::GenericClient,
  ) -> Result<GetLayoutStateRow, deadpool_postgres::tokio_postgres::Error> {
    let row = client.query_one(Self::QUERY, &self.as_slice()).await?;
    GetLayoutStateRow::from_row(&row)
  }
  pub async fn query_opt(
    &self,
    client: &impl deadpool_postgres::GenericClient,
  ) -> Result<Option<GetLayoutStateRow>, deadpool_postgres::tokio_postgres::Error> {
    let row = client.query_opt(Self::QUERY, &self.as_slice()).await?;
    match row {
      Some(row) => Ok(Some(GetLayoutStateRow::from_row(&row)?)),
      None => Ok(None),
    }
  }
  pub fn as_slice(&self) -> [&(dyn ToSql + Sync); 2] {
    [&self.user_id, &self.context_key]
  }
}
impl<'a> GetLayoutState<'a> {
  pub const fn builder() -> GetLayoutStateBuilder<'a, ((), ())> {
    GetLayoutStateBuilder {
      fields: ((), ()),
      _phantom: std::marker::PhantomData,
    }
  }
}
pub struct GetLayoutStateBuilder<'a, Fields = ((), ())> {
  fields: Fields,
  _phantom: std::marker::PhantomData<&'a ()>,
}
impl<'a, ContextKey> GetLayoutStateBuilder<'a, ((), ContextKey)> {
  pub fn user_id(self, user_id: &'a str) -> GetLayoutStateBuilder<'a, (&'a str, ContextKey)> {
    let ((), context_key) = self.fields;
    let _phantom = self._phantom;
    GetLayoutStateBuilder {
      fields: (user_id, context_key),
      _phantom,
    }
  }
}
impl<'a, UserId> GetLayoutStateBuilder<'a, (UserId, ())> {
  pub fn context_key(self, context_key: &'a str) -> GetLayoutStateBuilder<'a, (UserId, &'a str)> {
    let (user_id, ()) = self.fields;
    let _phantom = self._phantom;
    GetLayoutStateBuilder {
      fields: (user_id, context_key),
      _phantom,
    }
  }
}
impl<'a> GetLayoutStateBuilder<'a, (&'a str, &'a str)> {
  pub const fn build(self) -> GetLayoutState<'a> {
    let (user_id, context_key) = self.fields;
    GetLayoutState {
      user_id,
      context_key,
    }
  }
}
